services:
  - type: web # Change this to 'worker' if it's a background worker
    name: my-app # Feel free to change this name
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app" # IMPORTANT: Change this to your app's start command
    plan: free # Optional, you can remove this line
    packages:
      - name: build-essential
    envVars:
      # This is no longer needed as it's defined above
      # - key: PYTHON_VERSION
      #   value: 3.9.9 
      - key: GEMINI_API_KEY
        fromSecretFile: /etc/secrets/gemini_api_key
      - key: FIREBASE_SERVICE_ACCOUNT
        fromSecretFile: /etc/secrets/firebase_service_account